modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
credits="SyameimaruZheng and team"
description='''${mod_description}'''
logoFile="logo.jpg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="umapyoi"
    type="required"
    versionRange="[1.1.5-1.21.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
modId="curios"
type="required"
versionRange="[9.4.2+1.21.1,)"
ordering="AFTER"
side="BOTH"